/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as BuySellRouteImport } from './routes/buy-sell'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LuxRegistryRouteImport } from './routes/lux-registry'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as MonthlyDraftRouteImport } from './routes/monthly-draft'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as PipelineRunsRouteImport } from './routes/pipeline-runs'
import { Route as QuarterlyBriefDothtmlRouteImport } from './routes/quarterly-brief[.]html'
import { Route as ReportDothtmlRouteImport } from './routes/report[.]html'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SeoAuditRouteImport } from './routes/seo-audit'
import { Route as SeoDashboardRouteImport } from './routes/seo-dashboard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SowhatDebugRouteImport } from './routes/sowhat-debug'
import { Route as ThisWeekRouteImport } from './routes/this-week'
import { Route as AuthenticatedInternalRouteImport } from './routes/_authenticated/internal'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveWeekStartRouteImport } from './routes/archive.$weekStart'
import { Route as BriefsIndexRouteImport } from './routes/briefs.index'
import { Route as BriefsSlugRouteImport } from './routes/briefs.$slug'
import { Route as NeighborhoodsIndexRouteImport } from './routes/neighborhoods.index'
import { Route as NeighborhoodsSlugRouteImport } from './routes/neighborhoods.$slug'
import { Route as AuthenticatedMonthlyArchiveIndexRouteImport } from './routes/_authenticated/monthly-archive.index'
import { Route as AuthenticatedMonthlyArchiveMonthStartRouteImport } from './routes/_authenticated/monthly-archive.$monthStart'
import { Route as ApiPublicArchiveResnapshotRouteImport } from './routes/api/public/archive-resnapshot'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicMonthlyExportRouteImport } from './routes/api/public/monthly-export'
import { Route as ApiPublicPipelineAlertsRouteImport } from './routes/api/public/pipeline-alerts'
import { Route as ApiPublicReconciliationFlagsRouteImport } from './routes/api/public/reconciliation-flags'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'
import { Route as ApiPublicWeeklyExportRouteImport } from './routes/api/public/weekly-export'
import { Route as ApiPublicWeeklyReconciliationRouteImport } from './routes/api/public/weekly-reconciliation'
import { Route as NeighborhoodsSlugIndexRouteImport } from './routes/neighborhoods.$slug.index'
import { Route as NeighborhoodsSlugArchiveRouteImport } from './routes/neighborhoods.$slug.archive'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as NeighborhoodsSlugArchiveIndexRouteImport } from './routes/neighborhoods.$slug.archive.index'
import { Route as NeighborhoodsSlugArchiveMonthStartRouteImport } from './routes/neighborhoods.$slug.archive.$monthStart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySellRoute = BuySellRouteImport.update({
  id: '/buy-sell',
  path: '/buy-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxRegistryRoute = LuxRegistryRouteImport.update({
  id: '/lux-registry',
  path: '/lux-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyDraftRoute = MonthlyDraftRouteImport.update({
  id: '/monthly-draft',
  path: '/monthly-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRunsRoute = PipelineRunsRouteImport.update({
  id: '/pipeline-runs',
  path: '/pipeline-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarterlyBriefDothtmlRoute = QuarterlyBriefDothtmlRouteImport.update({
  id: '/quarterly-brief.html',
  path: '/quarterly-brief.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDothtmlRoute = ReportDothtmlRouteImport.update({
  id: '/report.html',
  path: '/report.html',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAuditRoute = SeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoDashboardRoute = SeoDashboardRouteImport.update({
  id: '/seo-dashboard',
  path: '/seo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SowhatDebugRoute = SowhatDebugRouteImport.update({
  id: '/sowhat-debug',
  path: '/sowhat-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisWeekRoute = ThisWeekRouteImport.update({
  id: '/this-week',
  path: '/this-week',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInternalRoute = AuthenticatedInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveWeekStartRoute = ArchiveWeekStartRouteImport.update({
  id: '/$weekStart',
  path: '/$weekStart',
  getParentRoute: () => ArchiveRoute,
} as any)
const BriefsIndexRoute = BriefsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BriefsRoute,
} as any)
const BriefsSlugRoute = BriefsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BriefsRoute,
} as any)
const NeighborhoodsIndexRoute = NeighborhoodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeighborhoodsRoute,
} as any)
const NeighborhoodsSlugRoute = NeighborhoodsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeighborhoodsRoute,
} as any)
const AuthenticatedMonthlyArchiveIndexRoute =
  AuthenticatedMonthlyArchiveIndexRouteImport.update({
    id: '/monthly-archive/',
    path: '/monthly-archive/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonthlyArchiveMonthStartRoute =
  AuthenticatedMonthlyArchiveMonthStartRouteImport.update({
    id: '/monthly-archive/$monthStart',
    path: '/monthly-archive/$monthStart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicArchiveResnapshotRoute =
  ApiPublicArchiveResnapshotRouteImport.update({
    id: '/api/public/archive-resnapshot',
    path: '/api/public/archive-resnapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMonthlyExportRoute = ApiPublicMonthlyExportRouteImport.update({
  id: '/api/public/monthly-export',
  path: '/api/public/monthly-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPipelineAlertsRoute = ApiPublicPipelineAlertsRouteImport.update({
  id: '/api/public/pipeline-alerts',
  path: '/api/public/pipeline-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconciliationFlagsRoute =
  ApiPublicReconciliationFlagsRouteImport.update({
    id: '/api/public/reconciliation-flags',
    path: '/api/public/reconciliation-flags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeeklyExportRoute = ApiPublicWeeklyExportRouteImport.update({
  id: '/api/public/weekly-export',
  path: '/api/public/weekly-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeeklyReconciliationRoute =
  ApiPublicWeeklyReconciliationRouteImport.update({
    id: '/api/public/weekly-reconciliation',
    path: '/api/public/weekly-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const NeighborhoodsSlugIndexRoute = NeighborhoodsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeighborhoodsSlugRoute,
} as any)
const NeighborhoodsSlugArchiveRoute =
  NeighborhoodsSlugArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => NeighborhoodsSlugRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const NeighborhoodsSlugArchiveIndexRoute =
  NeighborhoodsSlugArchiveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NeighborhoodsSlugArchiveRoute,
  } as any)
const NeighborhoodsSlugArchiveMonthStartRoute =
  NeighborhoodsSlugArchiveMonthStartRouteImport.update({
    id: '/$monthStart',
    path: '/$monthStart',
    getParentRoute: () => NeighborhoodsSlugArchiveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auth': typeof AuthRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/buy-sell': typeof BuySellRoute
  '/contact': typeof ContactRoute
  '/lux-registry': typeof LuxRegistryRoute
  '/monthly': typeof MonthlyRoute
  '/monthly-draft': typeof MonthlyDraftRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/pipeline-runs': typeof PipelineRunsRoute
  '/quarterly-brief.html': typeof QuarterlyBriefDothtmlRoute
  '/report.html': typeof ReportDothtmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/seo-audit': typeof SeoAuditRoute
  '/seo-dashboard': typeof SeoDashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sowhat-debug': typeof SowhatDebugRoute
  '/this-week': typeof ThisWeekRoute
  '/internal': typeof AuthenticatedInternalRoute
  '/api/agent': typeof ApiAgentRoute
  '/archive/$weekStart': typeof ArchiveWeekStartRoute
  '/briefs/$slug': typeof BriefsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRouteWithChildren
  '/archive/': typeof ArchiveIndexRoute
  '/briefs/': typeof BriefsIndexRoute
  '/neighborhoods/': typeof NeighborhoodsIndexRoute
  '/monthly-archive/$monthStart': typeof AuthenticatedMonthlyArchiveMonthStartRoute
  '/api/public/archive-resnapshot': typeof ApiPublicArchiveResnapshotRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/monthly-export': typeof ApiPublicMonthlyExportRoute
  '/api/public/pipeline-alerts': typeof ApiPublicPipelineAlertsRoute
  '/api/public/reconciliation-flags': typeof ApiPublicReconciliationFlagsRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/weekly-export': typeof ApiPublicWeeklyExportRoute
  '/api/public/weekly-reconciliation': typeof ApiPublicWeeklyReconciliationRoute
  '/neighborhoods/$slug/archive': typeof NeighborhoodsSlugArchiveRouteWithChildren
  '/monthly-archive/': typeof AuthenticatedMonthlyArchiveIndexRoute
  '/neighborhoods/$slug/': typeof NeighborhoodsSlugIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/neighborhoods/$slug/archive/$monthStart': typeof NeighborhoodsSlugArchiveMonthStartRoute
  '/neighborhoods/$slug/archive/': typeof NeighborhoodsSlugArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/buy-sell': typeof BuySellRoute
  '/contact': typeof ContactRoute
  '/lux-registry': typeof LuxRegistryRoute
  '/monthly': typeof MonthlyRoute
  '/monthly-draft': typeof MonthlyDraftRoute
  '/pipeline-runs': typeof PipelineRunsRoute
  '/quarterly-brief.html': typeof QuarterlyBriefDothtmlRoute
  '/report.html': typeof ReportDothtmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/seo-audit': typeof SeoAuditRoute
  '/seo-dashboard': typeof SeoDashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sowhat-debug': typeof SowhatDebugRoute
  '/this-week': typeof ThisWeekRoute
  '/internal': typeof AuthenticatedInternalRoute
  '/api/agent': typeof ApiAgentRoute
  '/archive/$weekStart': typeof ArchiveWeekStartRoute
  '/briefs/$slug': typeof BriefsSlugRoute
  '/archive': typeof ArchiveIndexRoute
  '/briefs': typeof BriefsIndexRoute
  '/neighborhoods': typeof NeighborhoodsIndexRoute
  '/monthly-archive/$monthStart': typeof AuthenticatedMonthlyArchiveMonthStartRoute
  '/api/public/archive-resnapshot': typeof ApiPublicArchiveResnapshotRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/monthly-export': typeof ApiPublicMonthlyExportRoute
  '/api/public/pipeline-alerts': typeof ApiPublicPipelineAlertsRoute
  '/api/public/reconciliation-flags': typeof ApiPublicReconciliationFlagsRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/weekly-export': typeof ApiPublicWeeklyExportRoute
  '/api/public/weekly-reconciliation': typeof ApiPublicWeeklyReconciliationRoute
  '/monthly-archive': typeof AuthenticatedMonthlyArchiveIndexRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/neighborhoods/$slug/archive/$monthStart': typeof NeighborhoodsSlugArchiveMonthStartRoute
  '/neighborhoods/$slug/archive': typeof NeighborhoodsSlugArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auth': typeof AuthRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/buy-sell': typeof BuySellRoute
  '/contact': typeof ContactRoute
  '/lux-registry': typeof LuxRegistryRoute
  '/monthly': typeof MonthlyRoute
  '/monthly-draft': typeof MonthlyDraftRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/pipeline-runs': typeof PipelineRunsRoute
  '/quarterly-brief.html': typeof QuarterlyBriefDothtmlRoute
  '/report.html': typeof ReportDothtmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/seo-audit': typeof SeoAuditRoute
  '/seo-dashboard': typeof SeoDashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sowhat-debug': typeof SowhatDebugRoute
  '/this-week': typeof ThisWeekRoute
  '/_authenticated/internal': typeof AuthenticatedInternalRoute
  '/api/agent': typeof ApiAgentRoute
  '/archive/$weekStart': typeof ArchiveWeekStartRoute
  '/briefs/$slug': typeof BriefsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRouteWithChildren
  '/archive/': typeof ArchiveIndexRoute
  '/briefs/': typeof BriefsIndexRoute
  '/neighborhoods/': typeof NeighborhoodsIndexRoute
  '/_authenticated/monthly-archive/$monthStart': typeof AuthenticatedMonthlyArchiveMonthStartRoute
  '/api/public/archive-resnapshot': typeof ApiPublicArchiveResnapshotRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/monthly-export': typeof ApiPublicMonthlyExportRoute
  '/api/public/pipeline-alerts': typeof ApiPublicPipelineAlertsRoute
  '/api/public/reconciliation-flags': typeof ApiPublicReconciliationFlagsRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/weekly-export': typeof ApiPublicWeeklyExportRoute
  '/api/public/weekly-reconciliation': typeof ApiPublicWeeklyReconciliationRoute
  '/neighborhoods/$slug/archive': typeof NeighborhoodsSlugArchiveRouteWithChildren
  '/_authenticated/monthly-archive/': typeof AuthenticatedMonthlyArchiveIndexRoute
  '/neighborhoods/$slug/': typeof NeighborhoodsSlugIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/neighborhoods/$slug/archive/$monthStart': typeof NeighborhoodsSlugArchiveMonthStartRoute
  '/neighborhoods/$slug/archive/': typeof NeighborhoodsSlugArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/archive'
    | '/auth'
    | '/briefs'
    | '/buy-sell'
    | '/contact'
    | '/lux-registry'
    | '/monthly'
    | '/monthly-draft'
    | '/neighborhoods'
    | '/pipeline-runs'
    | '/quarterly-brief.html'
    | '/report.html'
    | '/rss.xml'
    | '/seo-audit'
    | '/seo-dashboard'
    | '/sitemap.xml'
    | '/sowhat-debug'
    | '/this-week'
    | '/internal'
    | '/api/agent'
    | '/archive/$weekStart'
    | '/briefs/$slug'
    | '/neighborhoods/$slug'
    | '/archive/'
    | '/briefs/'
    | '/neighborhoods/'
    | '/monthly-archive/$monthStart'
    | '/api/public/archive-resnapshot'
    | '/api/public/lead'
    | '/api/public/monthly-export'
    | '/api/public/pipeline-alerts'
    | '/api/public/reconciliation-flags'
    | '/api/public/subscribe'
    | '/api/public/weekly-export'
    | '/api/public/weekly-reconciliation'
    | '/neighborhoods/$slug/archive'
    | '/monthly-archive/'
    | '/neighborhoods/$slug/'
    | '/lovable/email/transactional/preview'
    | '/neighborhoods/$slug/archive/$monthStart'
    | '/neighborhoods/$slug/archive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/buy-sell'
    | '/contact'
    | '/lux-registry'
    | '/monthly'
    | '/monthly-draft'
    | '/pipeline-runs'
    | '/quarterly-brief.html'
    | '/report.html'
    | '/rss.xml'
    | '/seo-audit'
    | '/seo-dashboard'
    | '/sitemap.xml'
    | '/sowhat-debug'
    | '/this-week'
    | '/internal'
    | '/api/agent'
    | '/archive/$weekStart'
    | '/briefs/$slug'
    | '/archive'
    | '/briefs'
    | '/neighborhoods'
    | '/monthly-archive/$monthStart'
    | '/api/public/archive-resnapshot'
    | '/api/public/lead'
    | '/api/public/monthly-export'
    | '/api/public/pipeline-alerts'
    | '/api/public/reconciliation-flags'
    | '/api/public/subscribe'
    | '/api/public/weekly-export'
    | '/api/public/weekly-reconciliation'
    | '/monthly-archive'
    | '/neighborhoods/$slug'
    | '/lovable/email/transactional/preview'
    | '/neighborhoods/$slug/archive/$monthStart'
    | '/neighborhoods/$slug/archive'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/archive'
    | '/auth'
    | '/briefs'
    | '/buy-sell'
    | '/contact'
    | '/lux-registry'
    | '/monthly'
    | '/monthly-draft'
    | '/neighborhoods'
    | '/pipeline-runs'
    | '/quarterly-brief.html'
    | '/report.html'
    | '/rss.xml'
    | '/seo-audit'
    | '/seo-dashboard'
    | '/sitemap.xml'
    | '/sowhat-debug'
    | '/this-week'
    | '/_authenticated/internal'
    | '/api/agent'
    | '/archive/$weekStart'
    | '/briefs/$slug'
    | '/neighborhoods/$slug'
    | '/archive/'
    | '/briefs/'
    | '/neighborhoods/'
    | '/_authenticated/monthly-archive/$monthStart'
    | '/api/public/archive-resnapshot'
    | '/api/public/lead'
    | '/api/public/monthly-export'
    | '/api/public/pipeline-alerts'
    | '/api/public/reconciliation-flags'
    | '/api/public/subscribe'
    | '/api/public/weekly-export'
    | '/api/public/weekly-reconciliation'
    | '/neighborhoods/$slug/archive'
    | '/_authenticated/monthly-archive/'
    | '/neighborhoods/$slug/'
    | '/lovable/email/transactional/preview'
    | '/neighborhoods/$slug/archive/$monthStart'
    | '/neighborhoods/$slug/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  AuthRoute: typeof AuthRoute
  BriefsRoute: typeof BriefsRouteWithChildren
  BuySellRoute: typeof BuySellRoute
  ContactRoute: typeof ContactRoute
  LuxRegistryRoute: typeof LuxRegistryRoute
  MonthlyRoute: typeof MonthlyRoute
  MonthlyDraftRoute: typeof MonthlyDraftRoute
  NeighborhoodsRoute: typeof NeighborhoodsRouteWithChildren
  PipelineRunsRoute: typeof PipelineRunsRoute
  QuarterlyBriefDothtmlRoute: typeof QuarterlyBriefDothtmlRoute
  ReportDothtmlRoute: typeof ReportDothtmlRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SeoAuditRoute: typeof SeoAuditRoute
  SeoDashboardRoute: typeof SeoDashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SowhatDebugRoute: typeof SowhatDebugRoute
  ThisWeekRoute: typeof ThisWeekRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiPublicArchiveResnapshotRoute: typeof ApiPublicArchiveResnapshotRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicMonthlyExportRoute: typeof ApiPublicMonthlyExportRoute
  ApiPublicPipelineAlertsRoute: typeof ApiPublicPipelineAlertsRoute
  ApiPublicReconciliationFlagsRoute: typeof ApiPublicReconciliationFlagsRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
  ApiPublicWeeklyExportRoute: typeof ApiPublicWeeklyExportRoute
  ApiPublicWeeklyReconciliationRoute: typeof ApiPublicWeeklyReconciliationRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-sell': {
      id: '/buy-sell'
      path: '/buy-sell'
      fullPath: '/buy-sell'
      preLoaderRoute: typeof BuySellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lux-registry': {
      id: '/lux-registry'
      path: '/lux-registry'
      fullPath: '/lux-registry'
      preLoaderRoute: typeof LuxRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-draft': {
      id: '/monthly-draft'
      path: '/monthly-draft'
      fullPath: '/monthly-draft'
      preLoaderRoute: typeof MonthlyDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-runs': {
      id: '/pipeline-runs'
      path: '/pipeline-runs'
      fullPath: '/pipeline-runs'
      preLoaderRoute: typeof PipelineRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarterly-brief.html': {
      id: '/quarterly-brief.html'
      path: '/quarterly-brief.html'
      fullPath: '/quarterly-brief.html'
      preLoaderRoute: typeof QuarterlyBriefDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report.html': {
      id: '/report.html'
      path: '/report.html'
      fullPath: '/report.html'
      preLoaderRoute: typeof ReportDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-audit': {
      id: '/seo-audit'
      path: '/seo-audit'
      fullPath: '/seo-audit'
      preLoaderRoute: typeof SeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-dashboard': {
      id: '/seo-dashboard'
      path: '/seo-dashboard'
      fullPath: '/seo-dashboard'
      preLoaderRoute: typeof SeoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sowhat-debug': {
      id: '/sowhat-debug'
      path: '/sowhat-debug'
      fullPath: '/sowhat-debug'
      preLoaderRoute: typeof SowhatDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-week': {
      id: '/this-week'
      path: '/this-week'
      fullPath: '/this-week'
      preLoaderRoute: typeof ThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/internal': {
      id: '/_authenticated/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof AuthenticatedInternalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/$weekStart': {
      id: '/archive/$weekStart'
      path: '/$weekStart'
      fullPath: '/archive/$weekStart'
      preLoaderRoute: typeof ArchiveWeekStartRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/briefs/': {
      id: '/briefs/'
      path: '/'
      fullPath: '/briefs/'
      preLoaderRoute: typeof BriefsIndexRouteImport
      parentRoute: typeof BriefsRoute
    }
    '/briefs/$slug': {
      id: '/briefs/$slug'
      path: '/$slug'
      fullPath: '/briefs/$slug'
      preLoaderRoute: typeof BriefsSlugRouteImport
      parentRoute: typeof BriefsRoute
    }
    '/neighborhoods/': {
      id: '/neighborhoods/'
      path: '/'
      fullPath: '/neighborhoods/'
      preLoaderRoute: typeof NeighborhoodsIndexRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
    '/neighborhoods/$slug': {
      id: '/neighborhoods/$slug'
      path: '/$slug'
      fullPath: '/neighborhoods/$slug'
      preLoaderRoute: typeof NeighborhoodsSlugRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
    '/_authenticated/monthly-archive/': {
      id: '/_authenticated/monthly-archive/'
      path: '/monthly-archive'
      fullPath: '/monthly-archive/'
      preLoaderRoute: typeof AuthenticatedMonthlyArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly-archive/$monthStart': {
      id: '/_authenticated/monthly-archive/$monthStart'
      path: '/monthly-archive/$monthStart'
      fullPath: '/monthly-archive/$monthStart'
      preLoaderRoute: typeof AuthenticatedMonthlyArchiveMonthStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/archive-resnapshot': {
      id: '/api/public/archive-resnapshot'
      path: '/api/public/archive-resnapshot'
      fullPath: '/api/public/archive-resnapshot'
      preLoaderRoute: typeof ApiPublicArchiveResnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monthly-export': {
      id: '/api/public/monthly-export'
      path: '/api/public/monthly-export'
      fullPath: '/api/public/monthly-export'
      preLoaderRoute: typeof ApiPublicMonthlyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pipeline-alerts': {
      id: '/api/public/pipeline-alerts'
      path: '/api/public/pipeline-alerts'
      fullPath: '/api/public/pipeline-alerts'
      preLoaderRoute: typeof ApiPublicPipelineAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconciliation-flags': {
      id: '/api/public/reconciliation-flags'
      path: '/api/public/reconciliation-flags'
      fullPath: '/api/public/reconciliation-flags'
      preLoaderRoute: typeof ApiPublicReconciliationFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-export': {
      id: '/api/public/weekly-export'
      path: '/api/public/weekly-export'
      fullPath: '/api/public/weekly-export'
      preLoaderRoute: typeof ApiPublicWeeklyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-reconciliation': {
      id: '/api/public/weekly-reconciliation'
      path: '/api/public/weekly-reconciliation'
      fullPath: '/api/public/weekly-reconciliation'
      preLoaderRoute: typeof ApiPublicWeeklyReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug/': {
      id: '/neighborhoods/$slug/'
      path: '/'
      fullPath: '/neighborhoods/$slug/'
      preLoaderRoute: typeof NeighborhoodsSlugIndexRouteImport
      parentRoute: typeof NeighborhoodsSlugRoute
    }
    '/neighborhoods/$slug/archive': {
      id: '/neighborhoods/$slug/archive'
      path: '/archive'
      fullPath: '/neighborhoods/$slug/archive'
      preLoaderRoute: typeof NeighborhoodsSlugArchiveRouteImport
      parentRoute: typeof NeighborhoodsSlugRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug/archive/': {
      id: '/neighborhoods/$slug/archive/'
      path: '/'
      fullPath: '/neighborhoods/$slug/archive/'
      preLoaderRoute: typeof NeighborhoodsSlugArchiveIndexRouteImport
      parentRoute: typeof NeighborhoodsSlugArchiveRoute
    }
    '/neighborhoods/$slug/archive/$monthStart': {
      id: '/neighborhoods/$slug/archive/$monthStart'
      path: '/$monthStart'
      fullPath: '/neighborhoods/$slug/archive/$monthStart'
      preLoaderRoute: typeof NeighborhoodsSlugArchiveMonthStartRouteImport
      parentRoute: typeof NeighborhoodsSlugArchiveRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInternalRoute: typeof AuthenticatedInternalRoute
  AuthenticatedMonthlyArchiveMonthStartRoute: typeof AuthenticatedMonthlyArchiveMonthStartRoute
  AuthenticatedMonthlyArchiveIndexRoute: typeof AuthenticatedMonthlyArchiveIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInternalRoute: AuthenticatedInternalRoute,
  AuthenticatedMonthlyArchiveMonthStartRoute:
    AuthenticatedMonthlyArchiveMonthStartRoute,
  AuthenticatedMonthlyArchiveIndexRoute: AuthenticatedMonthlyArchiveIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArchiveRouteChildren {
  ArchiveWeekStartRoute: typeof ArchiveWeekStartRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveWeekStartRoute: ArchiveWeekStartRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface BriefsRouteChildren {
  BriefsSlugRoute: typeof BriefsSlugRoute
  BriefsIndexRoute: typeof BriefsIndexRoute
}

const BriefsRouteChildren: BriefsRouteChildren = {
  BriefsSlugRoute: BriefsSlugRoute,
  BriefsIndexRoute: BriefsIndexRoute,
}

const BriefsRouteWithChildren =
  BriefsRoute._addFileChildren(BriefsRouteChildren)

interface NeighborhoodsSlugArchiveRouteChildren {
  NeighborhoodsSlugArchiveMonthStartRoute: typeof NeighborhoodsSlugArchiveMonthStartRoute
  NeighborhoodsSlugArchiveIndexRoute: typeof NeighborhoodsSlugArchiveIndexRoute
}

const NeighborhoodsSlugArchiveRouteChildren: NeighborhoodsSlugArchiveRouteChildren =
  {
    NeighborhoodsSlugArchiveMonthStartRoute:
      NeighborhoodsSlugArchiveMonthStartRoute,
    NeighborhoodsSlugArchiveIndexRoute: NeighborhoodsSlugArchiveIndexRoute,
  }

const NeighborhoodsSlugArchiveRouteWithChildren =
  NeighborhoodsSlugArchiveRoute._addFileChildren(
    NeighborhoodsSlugArchiveRouteChildren,
  )

interface NeighborhoodsSlugRouteChildren {
  NeighborhoodsSlugArchiveRoute: typeof NeighborhoodsSlugArchiveRouteWithChildren
  NeighborhoodsSlugIndexRoute: typeof NeighborhoodsSlugIndexRoute
}

const NeighborhoodsSlugRouteChildren: NeighborhoodsSlugRouteChildren = {
  NeighborhoodsSlugArchiveRoute: NeighborhoodsSlugArchiveRouteWithChildren,
  NeighborhoodsSlugIndexRoute: NeighborhoodsSlugIndexRoute,
}

const NeighborhoodsSlugRouteWithChildren =
  NeighborhoodsSlugRoute._addFileChildren(NeighborhoodsSlugRouteChildren)

interface NeighborhoodsRouteChildren {
  NeighborhoodsSlugRoute: typeof NeighborhoodsSlugRouteWithChildren
  NeighborhoodsIndexRoute: typeof NeighborhoodsIndexRoute
}

const NeighborhoodsRouteChildren: NeighborhoodsRouteChildren = {
  NeighborhoodsSlugRoute: NeighborhoodsSlugRouteWithChildren,
  NeighborhoodsIndexRoute: NeighborhoodsIndexRoute,
}

const NeighborhoodsRouteWithChildren = NeighborhoodsRoute._addFileChildren(
  NeighborhoodsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  AuthRoute: AuthRoute,
  BriefsRoute: BriefsRouteWithChildren,
  BuySellRoute: BuySellRoute,
  ContactRoute: ContactRoute,
  LuxRegistryRoute: LuxRegistryRoute,
  MonthlyRoute: MonthlyRoute,
  MonthlyDraftRoute: MonthlyDraftRoute,
  NeighborhoodsRoute: NeighborhoodsRouteWithChildren,
  PipelineRunsRoute: PipelineRunsRoute,
  QuarterlyBriefDothtmlRoute: QuarterlyBriefDothtmlRoute,
  ReportDothtmlRoute: ReportDothtmlRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SeoAuditRoute: SeoAuditRoute,
  SeoDashboardRoute: SeoDashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SowhatDebugRoute: SowhatDebugRoute,
  ThisWeekRoute: ThisWeekRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiPublicArchiveResnapshotRoute: ApiPublicArchiveResnapshotRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicMonthlyExportRoute: ApiPublicMonthlyExportRoute,
  ApiPublicPipelineAlertsRoute: ApiPublicPipelineAlertsRoute,
  ApiPublicReconciliationFlagsRoute: ApiPublicReconciliationFlagsRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
  ApiPublicWeeklyExportRoute: ApiPublicWeeklyExportRoute,
  ApiPublicWeeklyReconciliationRoute: ApiPublicWeeklyReconciliationRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
